services:
  - type: web
    name: chroma-db
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile

    envVars:
      - key: IS_PERSISTENT
        value: TRUE

      - key: ALLOW_RESET
        value: TRUE